name: Test and Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "my-very-secret-key"
          heroku_app_name: "my-app-name"
          heroku_email: "my-email-address"
