name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          PGHOST: ${{ secrects.PGHOST }}
          PGDATABASE: ${{ secrects.PGDATABASE }}
          PGPASSWORD: ${{ secrects.PGPASSWORD }}
