name: Test and Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          hostname: ${{ secrects.PGHOST }}
          database: ${{ secrects.PGDATABASE }}
          user: ${{ secrects.PGDATABASE }}
          password: ${{ secrects.PGPASSWORD }}
